# Generated by Django 4.2.14 on 2024-07-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0002_movie_delete_tablo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
